var num1 = -69;
var num2 = .69;
var num3 = 6969;
var num4 = (23*3);
var string1 = "sixty";
var string2 = "nine";
var string3 = "69";
var sixtyninebad = false;
var sixtyninegood = true;
console.log('first number:', num1);
console.log('second number:', num2);
console.log('third number:', num3);
console.log('fourth number:', num4);
console.log('first string:', string1);
console.log('second string:', string2);
console.log('third string:', string3);
console.log('false boolean:', sixtyninebad);
console.log('true boolean:', sixtyninegood);
console.log('undefined string:', sixtyninenotdefined);
